version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - ./db/mysql:/var/lib/mysql:cached

  web: &app_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/actindi
      - bundle_install:/usr/local/bundle   
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    
volumes:
  bundle_install:
    driver: local
